import turtle
turtle.speed(0)
turtle.penup()
turtle.goto(-350,225)
turtle.pendown()
def draw_triangle(length):
    for i in range(7):
        
        turtle.forward(length)
        turtle.left(120)
        turtle.forward(length)
        turtle.left(120)
        turtle.forward(length)
        turtle.left(120)
        turtle.penup()
        turtle.forward(length+10)
        turtle.pendown()
    turtle.right(90)
    turtle.penup()
    turtle.forward(length-50)
    turtle.right(90)
    turtle.pendown()
    for i in range(7):
        
        turtle.forward(length)
        turtle.left(120)
        turtle.forward(length)
        turtle.left(120)
        turtle.forward(length)
        turtle.left(120)
        turtle.penup()
        turtle.forward(length+10)
        turtle.pendown()
    turtle.left(90)
    turtle.penup()
    turtle.forward(length+100)
    turtle.left(90)
    turtle.pendown()
    for i in range(7):
        
        turtle.forward(length)
        turtle.left(120)
        turtle.forward(length)
        turtle.left(120)
        turtle.forward(length)
        turtle.left(120)
        turtle.penup()
        turtle.forward(length+10)
        turtle.pendown()
    turtle.right(90)
    turtle.penup()
    turtle.forward(length-50)
    turtle.right(90)
    turtle.pendown()
    for i in range(7):
        turtle.forward(length)
        turtle.left(120)
        turtle.forward(length)
        turtle.left(120)
        turtle.forward(length)
        turtle.left(120)
        turtle.penup()
        turtle.forward(length+10)
        turtle.pendown()
    turtle.left(90)
    turtle.penup()
    turtle.forward(length+100)
    turtle.left(90)
    turtle.pendown()
    for i in range(7):
        turtle.forward(length)
        turtle.left(120)
        turtle.forward(length)
        turtle.left(120)
        turtle.forward(length)
        turtle.left(120)
        turtle.penup()
        turtle.forward(length+10)
        turtle.pendown()
draw_triangle(100)
